url: 'https://b08x.github.io'
baseurl: ''
title: 'syncopated semantics'

plugins:
  - jekyll-postcss-v2
  - jekyll-target-blank

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - scratchpad.html


permalink: /:slugified_categories/:title
