url: 'https://b08x.github.io'
baseurl: ''
title: 'syncopated semantics'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock


permalink: /:slugified_categories/:title
