url: 'https://b08x.github.io'
baseurl: ''
title: 'syncopated semantics'

plugins:
  - jekyll-postcss-v2
  - jekyll-target-blank
  - jekyll-spaceship

jekyll-spaceship:
  mermaid-processor:
    css:
      class: 'mermaid!'
    config:
      theme: dark

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - scratchpad.html

permalink: /:slugified_categories/:title

defaults:
  - scope:
      path: assets/img/favicons
    values:
      swcache: true