graph TB
subgraph LinuxSystemsEngineering
style LSE1 fill:#333333,stroke:#ffffff, stroke-width: 2px, color:#ffffff
LSE1((Linux<br>Administration))
style LSE2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
LSE2((Networking))
style LSE3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
LSE3((Security))
style LSE4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
LSE4((Performance<br>Tuning))
style LSE5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
LSE5((Backup &<br>Recovery))
style LSE6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
LSE6((Shell<br>Scripting))
style LSE7 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
LSE7((System<br>Monitoring))
end

subgraph AnsibleAutomation
style AA1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
AA1((Playbook<br>Creation))
style AA2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
AA2((Role<br>Management))
style AA3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
AA3((Inventory<br>Management))
style AA4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
AA4((Module<br>Development))
style AA5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
AA5((Error<br>Handling))
style AA6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
AA6((Cloud<br>Integration))
end

subgraph CloudComputing
style CC1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CC1((AWS))
style CC2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CC2((GCP))
style CC3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CC3((Azure))
style CC4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CC4((OpenStack))
style CC5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CC5((Cloud<br>Security))
style CC6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CC6((Cloud<br>Networking))
end

subgraph Containerization
style CZ1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CZ1((Docker))
style CZ2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CZ2((Kubernetes))
style CZ3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CZ3((OpenShift))
style CZ4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CZ4((Container<br>Security))
style CZ5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CZ5((Container<br>Networking))
style CZ6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
CZ6((Container<br>Orchestration))
end

subgraph DevOpsPractices
style DOP1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
DOP1((CI/CD))
style DOP2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
DOP2((IaC))
style DOP3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
DOP3((Version<br>Control))
style DOP4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
DOP4((Testing))
style DOP5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
DOP5((Monitoring))
style DOP6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
DOP6((Logging))
end

subgraph Networking
style NT1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
NT1((IP<br>Networking))
style NT2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
NT2((Firewalls))
style NT3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
NT3((VPN))
style NT4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
NT4((Load<br>Balancing))
style NT5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
NT5((Network<br>Troubleshooting))
style NT6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
NT6((Network<br>Security))
end

subgraph Security
style SEC1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
SEC1((System<br>Hardening))
style SEC2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
SEC2((Intrusion<br>Detection))
style SEC3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
SEC3((Patch<br>Management))
style SEC4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
SEC4((Access<br>Control))
style SEC5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
SEC5((Cryptography))
style SEC6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
SEC6((Compliance))
end

subgraph Programming
style PRG1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PRG1((Python))
style PRG2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PRG2((Bash))
style PRG3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PRG3((YAML))
style PRG4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PRG4((JSON))
style PRG5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PRG5((REST<br>APIs))
style PRG6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PRG6((Git))
end

subgraph ProblemSolving
style PS1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PS1((Troubleshooting))
style PS2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PS2((Root Cause<br>Analysis))
style PS3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PS3((Performance<br>Optimization))
style PS4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PS4((Disaster<br>Recovery))
style PS5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PS5((Documentation))
style PS6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PS6((Communication))
end

subgraph ProjectManagement
style PM1 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PM1((Agile<br>Methodologies))
style PM2 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PM2((Scrum))
style PM3 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PM3((Kanban))
style PM4 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PM4((Risk<br>Management))
style PM5 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PM5((Stakeholder<br>Communication))
style PM6 fill:#333333,stroke:#ffffff, stroke-width: 2px,color:#ffffff
PM6((Resource<br>Allocation))
end

LSE1-->AA1
LSE2-->NT1
LSE3-->SEC1
LSE4-->PS3
LSE5-->PS4
LSE6-->PRG2

AA1-->DOP1
AA2-->DOP2
AA3-->DOP3
AA4-->PRG5
AA5-->PS1
AA6-->CC1

CZ1-->LSE6
CZ2-->AA6
CZ3-->AA6
CZ4-->LSE3
CZ5-->LSE2
CZ6-->AA2

DOP1-->AA1
DOP1-->DOP6
DOP1-->DOP3
DOP1-->DOP4
DOP2-->PM3
DOP3-->PRG6
DOP4-->PM4
DOP5-->LSE7
DOP6-->PS1

NT1-->LSE2
NT2-->LSE3
NT3-->CZ5
NT4-->CZ6
NT5-->PS1
NT6-->LSE3

SEC1-->LSE3
SEC2-->LSE3
SEC3-->PM4
SEC4-->CZ4
SEC5-->PRG3
SEC6-->PM1

PRG1-->DOP4
PRG2-->LSE6
PRG3-->AA1
PRG4-->LSE7
PRG5-->CZ3
PRG6-->DOP3

PS1-->DOP6
PS2-->SEC2
PS3-->LSE4
PS4-->LSE5
PS5-->PM5
PS6-->PM5

PM1-->DOP1
PM2-->DOP1
PM3-->DOP1
PM4-->DOP4
PM5-->PS6
PM6-->DOP2

linkStyle default interpolate basis
